package GUI;


import clases.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David fernando Montes Florián
 * @SENA 2022 - 
 *      DESARROLLO DE APLICACIONES CON INTERFAZ GRAFICA, MANEJO DE EVENTOS, 
 *      CLASES Y OBJETOS: JAVA (2531803)
 * 
 * Pendiente creación e integración al proyecto de la clase vacaciones.
 * Pendiente operaciones con intereses.
 * 
 * Posibilidad de creación de cuentas de Ahorro e Inversión.
 * Posibilidad de creación de prefiles de usuario: "Cliente", "Empleado" y "Casa Inversionista".
 * Manejo de los montos minimos de la cuenta, tanto para creación como para el saldo permanente.
 * 
 * Búsqueda de cuentas registradas por ID.
 * Listar todas las cuentas registradas.
 * 
 * Depósito y retiro (respeta montos mínimos establecidos) funcionando correctamente. 
 * 
 */
public class BancoGUI extends javax.swing.JFrame {

    private String tipoRegistro="";
    private String nombre="";
    private String documento="";
    private String telefono="";
    private String direccion="";
    private String correo="";
    private String tipoCuenta="";
    double deposito;
    double retiro;
    double saldo;
    int porcientoAhorro;
    int porcientoInteresMes;
            
    List<Cuentas> listCuentas= new ArrayList<>();
    List<Persona> listPersonas= new ArrayList<>();
    List<Persona> listCasaInversoras= new ArrayList<>();
    
    List<String> listNivelesRiesgo= new ArrayList<>();
    List<String> listMontos= new ArrayList<>();
    List<String> listPlazos= new ArrayList<>();
    
    private String msj;
    private String fechaCuenta;
    
    private CtaAhorros objCtaAhorros;
    private CtaInversion objCtaInversion;
    private Cliente objCliente;
    private CasaInversora objCasaInversora;
    private int porcientoRetorno;
    private String sueldoEmpleado;
    private String cargo;
    private Empleado objEmpleado;
    private String documentotrns;
    private String tipoCuentaTrns;
    private String montoTrns;
    private boolean hacerTrns;
    private Cuentas objCuentas= new Cuentas("","","");
    private String nombreInversora;
    private Persona objPersona= new Persona("", "", "", "", "");
    

    public void addCasaInversionista(CasaInversora objCasa){
        this.listCasaInversoras.add(objCasa);
    }
    
    /**
     * Creates new form BancoGUI
     */
    public BancoGUI() {
        initComponents();
        postInit();
    }

    
    private void postInit(){
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipoCuenta_jComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tipoRegistro_jComboBox = new javax.swing.JComboBox<>();
        btnDoRegistro = new javax.swing.JButton();
        btnCancelRegistro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tipoTransaccion_jComboBox = new javax.swing.JComboBox<>();
        txtDocumento_Tran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMonto_trns = new javax.swing.JTextField();
        btnContinuar_Trns = new javax.swing.JButton();
        btnCancel_Trns = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados_jTextArea = new javax.swing.JTextArea();
        btnListarCuentas = new javax.swing.JButton();
        btnLimpiarResultados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Software De Gestión Bancaria");

        txtNombre.setToolTipText("");

        jLabel3.setText("Nombre");

        txtDocumento.setToolTipText("");

        jLabel4.setText("Documento");

        txtTelefono.setToolTipText("");

        jLabel5.setText("Teléfono");

        txtDireccion.setToolTipText("");

        jLabel6.setText("Dirección");

        txtCorreo.setToolTipText("");

        jLabel7.setText("Correo");

        jLabel8.setText("Tipo Cuenta");

        tipoCuenta_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Ahorros", "Inversión" }));

        jLabel9.setText("Tipo Registro");

        tipoRegistro_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cliente", "Empleado", "Casa Inversora" }));

        btnDoRegistro.setText("Crear");
        btnDoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoRegistroActionPerformed(evt);
            }
        });

        btnCancelRegistro.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDocumento))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefono))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDireccion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorreo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoCuenta_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelRegistro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoRegistro_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoRegistro_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCuenta_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnDoRegistro)
                    .addComponent(btnCancelRegistro))
                .addGap(4, 4, 4))
        );

        jTabbedPane1.addTab("Registros", jPanel2);

        jLabel10.setText("Transacción");

        tipoTransaccion_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Depósito", "Retiro", "Consulta" }));

        txtDocumento_Tran.setToolTipText("Documento");

        jLabel11.setText("Documento");

        jLabel13.setText("Monto $$$");

        txtMonto_trns.setToolTipText("Monto Económico");

        btnContinuar_Trns.setText("Continuar");
        btnContinuar_Trns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuar_TrnsActionPerformed(evt);
            }
        });

        btnCancel_Trns.setText("Cancelar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnContinuar_Trns, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel_Trns, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocumento_Tran)
                    .addComponent(tipoTransaccion_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMonto_trns, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tipoTransaccion_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumento_Tran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto_trns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar_Trns)
                    .addComponent(btnCancel_Trns))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transacciones", jPanel3);

        resultados_jTextArea.setColumns(20);
        resultados_jTextArea.setRows(5);
        jScrollPane1.setViewportView(resultados_jTextArea);

        btnListarCuentas.setText("Listar");
        btnListarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCuentasActionPerformed(evt);
            }
        });

        btnLimpiarResultados.setText("Reinicio");
        btnLimpiarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(btnListarCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListarCuentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(btnLimpiarResultados))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDatos(){
        int tR = this.tipoRegistro_jComboBox.getSelectedIndex();
        tipoRegistro = tipoRegistro_jComboBox.getItemAt(tR);
        nombre= this.txtNombre.getText();
        documento= this.txtDocumento.getText();
        telefono= this.txtTelefono.getText();
        direccion= this.txtDireccion.getText();
        correo= this.txtCorreo.getText();
        int tC= this.tipoCuenta_jComboBox.getSelectedIndex();
        tipoCuenta= this.tipoCuenta_jComboBox.getItemAt(tC);        
    }
    
    private void btnDoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoRegistroActionPerformed
        addDatos();
        if(tipoRegistro.isEmpty()||nombre.isEmpty()||documento.isEmpty()||telefono.isEmpty()||
                  direccion.isEmpty()||correo.isEmpty()||tipoCuenta.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos requeridos\ndeben ser diligenciados!");
        }else{/*
            if(tipoCuenta.equalsIgnoreCase("Casa Inversora")){
                crearCasaInversora();
            }else{*/
                crearPersona();
                crearCuenta();
            //}            
            limpiarCampos();
        }
    }//GEN-LAST:event_btnDoRegistroActionPerformed

    private void crearCasaInversora(){
        this.objCasaInversora= new 
            CasaInversora( listNivelesRiesgo, listMontos, listPlazos, porcientoRetorno, nombre, documento, telefono, direccion, correo);
        objCuentas.setTipoRegistro(tipoRegistro);
        this.listCasaInversoras.add(objCasaInversora);
        this.listPersonas.add(objCasaInversora);
        System.out.println("CasaInversora:"+objCasaInversora.getNombre()+" creada correctamente.");                
    }
    
    private void crearPersona(){
        int tR = tipoRegistro_jComboBox.getSelectedIndex();
        switch (tR) {
            case 0:
                JOptionPane.showMessageDialog(null, "Seleccione el tipo de registro.");
                break;
            case 1:
                System.out.println("CrearCliente");
                objCliente= new Cliente( fechaCuenta, nombre, documento, telefono, direccion, correo);
                System.out.println( "Creado el cliente: "+ objCliente.getNombre()+ ", idCliente: "+ documento);
                this.listPersonas.add(objCliente);
                break;
            case 2:
                System.out.println("crearEmpleado");
                msj= "Ingrese el cargo del empleado.";
                cargo = JOptionPane.showInputDialog(null, msj);
                msj= "Sueldo asignado? ";
                sueldoEmpleado = JOptionPane.showInputDialog(null, msj);
                objEmpleado= new Empleado(cargo, fechaCuenta, sueldoEmpleado, nombre, documento, telefono, direccion, correo);
                this.listPersonas.add(objEmpleado);
                System.out.println( "Creado el empleado: "+ objEmpleado.getNombre()+ ", idEmpleado: "+ documento);
                break;
            case 3:
                System.out.println("crearCasaInversora");
                crearCasaInversora();
                break;
            default:
                throw new AssertionError();
        }
    }
    
    private void limpiarCampos(){
        this.tipoRegistro_jComboBox.setSelectedIndex(0);
        this.txtNombre.setText("");
        this.txtDocumento.setText("");
        this.txtTelefono.setText("");
        this.txtDireccion.setText("");
        this.txtCorreo.setText("");
        this.tipoCuenta_jComboBox.setSelectedIndex(0);
    }
    
    private void crearCuenta(){
        int tC = this.tipoCuenta_jComboBox.getSelectedIndex();
        switch (tC) {
            case 0:
                JOptionPane.showMessageDialog(null, "Seleccione el tipo de cuenta.");
                break;
            case 1:
                System.out.println("Crear cuenta Ahorros.");
                String paa = JOptionPane.showInputDialog(null, "Ingrese el Porcentaje De Ahorro Anual establecido.");
                porcientoAhorro= Integer.valueOf(paa);
                objCtaAhorros= new CtaAhorros( porcientoAhorro, porcientoInteresMes, documento, fechaCuenta, tipoCuenta);
                this.listCuentas.add(objCtaAhorros);
                hacerDeposito(objCtaAhorros);
                JOptionPane.showMessageDialog(null,"FinDeposito:"+ msj);
                break;

            case 2:
                System.out.println("Crear cuenta Inversión.");
                if(tipoCuenta_jComboBox.getSelectedIndex()==3){//Si es casa inversora...
                    nombreInversora=nombre;
                    msj="Ingrese el porcentaje de retorno de la Inversión.";
                    msj= JOptionPane.showInputDialog(msj);                    
                    porcientoRetorno=Integer.valueOf(msj);
                    objCuentas.setTipoRegistro(tipoRegistro);
                }else{
                    porcientoRetorno=0;
                }
                //objCtaInversion.setTipoRegistro(this.);
                objCtaInversion= new CtaInversion( documento, nombreInversora, fechaCuenta, tipoCuenta, porcientoRetorno, tipoRegistro);
                this.listCuentas.add(objCtaInversion);
                hacerDeposito(objCtaInversion);
                JOptionPane.showMessageDialog(null,"FinDeposito Inicial:"+ msj);
                
                break;
            default:
                System.out.println("Crear cuenta opción por defecto");
        }
        JOptionPane.showMessageDialog(null, "Se creó la cuenta "+ tipoCuenta+ " correctamente.");            
    }
    
    private String hacerDeposito(Cuentas cuenta){
        String depositoLetras = JOptionPane.showInputDialog("Monto del Deposito?");
        deposito= Double.valueOf(depositoLetras);
        msj = cuenta.hacerDeposito(deposito, cuenta);
        return msj;
    }
    
    private void hacerRetiro(){
        String retiroLetras = JOptionPane.showInputDialog("Monto del retiro?");
        deposito= Double.valueOf(retiroLetras);
        String estadoRetiro=objCtaAhorros.hacerRetiro(retiro, this.objCuentas);
        JOptionPane.showMessageDialog(null,"FinRetiro:"+ estadoRetiro);
    }
    
    
    private void btnListarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCuentasActionPerformed
        int cantCuentas = this.listCuentas.size();
        int cantPersonas = this.listPersonas.size();
        
            System.out.println("________________________________________________");
        for( int i=0; i<cantCuentas;i++){
            objCuentas= listCuentas.get(i);
            objPersona= listPersonas.get(i);
            this.nombre= objPersona.getNombre();
            this.nombre= objPersona.getCargo();
            this.correo= objPersona.getCorreo();
            this.direccion= objPersona.getDireccion();
            this.telefono= objPersona.getTelefono();
            this.documento= objCuentas.getIdTitular();
            this.saldo= objCuentas.getSaldo();
            this.tipoCuenta= objCuentas.getTipoCuenta();          
            /*this.porcientoInteresMes= objCuentas.getObjCtaAhorros().getPorcentajeInteresesMes();          
            this.porcientoAhorro= objCuentas.getObjCtaAhorros().getPorcentajeAhorro();          
            this.porcientoRetorno= objCuentas.getObjCtaInversion().getPorcientoRetorno();*/
            msj= "\n >>>  Cuenta "+i+
                    ": \n\tID: "+ documento+ 
                    "\n\tTitular: "+nombre+ 
                    "\n\tCargo: "+cargo+ 
                    "\n\tTeléfono: "+ telefono+ 
                    "\n\tCorreo: "+ correo+ 
                    "\n\tDirección: "+ direccion+
                    "\n\tSaldo: "+ saldo+ 
                    "\n\tTipo: "+ tipoCuenta+
                    "\n\tPorcentaje Interés Mensual: "+ porcientoInteresMes+ 
                    "\n\tPorcentaje De Retorno: "+ porcientoRetorno;
            System.out.println( msj+ "\n________________________________________________");
            this.resultados_jTextArea.setText( resultados_jTextArea.getText()+ "\n"+ msj);
        }
    }//GEN-LAST:event_btnListarCuentasActionPerformed

    private void getFecha(){
        
    }
    
    private void validarTransaccion(){
        documentotrns = this.txtDocumento_Tran.getText();
        //tipoCuentaTrns = this.txtTipoCuenta_trans.getText();
        montoTrns = this.txtMonto_trns.getText();
        if(listCuentas.size()>0){
            for(int i=0; i<listCuentas.size();i++){
                String idTit = this.listCuentas.get(i).getIdTitular();
                try {
                    if(idTit.equalsIgnoreCase(documentotrns)){
                        msj="Encontrada la cuenta correspondiente.";
                        this.objCuentas= this.listCuentas.get(i);
                        hacerTrns=true;
                        break;
                    }else {
                        hacerTrns=false;                
                        msj="NO encontrada la cuenta correspondiente.";
                    }
                } catch (NullPointerException npe) {
                    msj="NO se encontraron cuentas\nregistradas en el sistema.";
                } catch (Exception e) {
                    msj="Fallo inesperado:\n"+e.getLocalizedMessage();
                }
            }
        }else{
            msj="NO se encontraron cuentas\nregistradas en el sistema.";
        }
        JOptionPane.showConfirmDialog(rootPane, msj);
        System.out.println(msj);
    }
    
    private void btnContinuar_TrnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuar_TrnsActionPerformed
        validarTransaccion();
        if(hacerTrns){
            System.out.println("Cuenta válida.");
            int sel = tipoTransaccion_jComboBox.getSelectedIndex();
            switch (sel) {
                case 0:
                    break;
                case 1:
                    System.out.println("Hacer Deposito");
                String resDeposito = this.objCuentas.hacerDeposito(Double.valueOf(montoTrns), this.objCuentas);
                    JOptionPane.showInternalMessageDialog(null, "Resultado Del Depósito: "+ resDeposito);
                    break;

                case 2:
                    System.out.println("Hacer Retiro");
                    String resRetiro = this.objCuentas.hacerRetiro(Double.valueOf(montoTrns), this.objCuentas);
                    JOptionPane.showMessageDialog(null, "Resultado Del Retiro: "+ resRetiro);
                    break;

                case 3:
                    System.out.println("Hacer Consulta");   
                    this.documento= this.txtDocumento_Tran.getText().trim();
                    buscarID(documento);
                    break;
                default:
                    break;
            }
            
        }
    }//GEN-LAST:event_btnContinuar_TrnsActionPerformed

    private void btnLimpiarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarResultadosActionPerformed
        this.resultados_jTextArea.setText("\n");
    }//GEN-LAST:event_btnLimpiarResultadosActionPerformed

    private void buscarID(String documentoBuscar){
        int cantCuentas = this.listCuentas.size();
        int cantPersonas = this.listPersonas.size();
        
            System.out.println("________________________________________________");
        for( int i=0; i<cantCuentas;i++){
            objCuentas= listCuentas.get(i);
            objPersona= listPersonas.get(i);            
            this.documento= objCuentas.getIdTitular();
            
            if(this.documento.equalsIgnoreCase(documentoBuscar)){
                this.nombre= objPersona.getNombre();
                this.correo= objPersona.getCorreo();
                this.direccion= objPersona.getDireccion();
                this.telefono= objPersona.getTelefono();
                this.saldo= objCuentas.getSaldo();
                this.tipoCuenta= objCuentas.getTipoCuenta();          
                /*this.porcientoInteresMes= objCuentas.getObjCtaAhorros().getPorcentajeInteresesMes();          
                this.porcientoAhorro= objCuentas.getObjCtaAhorros().getPorcentajeAhorro();          
                this.porcientoRetorno= objCuentas.getObjCtaInversion().getPorcientoRetorno();*/
                msj= "\n >>> Busqueda De Cuenta Por ID."+
                        ": \n\tID: "+ documento+ 
                        "\n\tTitular: "+nombre+ 
                        "\n\tTeléfono: "+ telefono+ 
                        "\n\tCorreo: "+ correo+ 
                        "\n\tDirección: "+ direccion+
                        "\n\tSaldo: "+ saldo+ 
                        "\n\tTipo: "+ tipoCuenta+
                        "\n\tPorcentaje Interés Mensual: "+ porcientoInteresMes+ 
                        "\n\tPorcentaje De Retorno: "+ porcientoRetorno;
                System.out.println( msj+ "\n________________________________________________");
                this.resultados_jTextArea.setText( resultados_jTextArea.getText()+ "\n"+ msj);
                break;
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRegistro;
    private javax.swing.JButton btnCancel_Trns;
    private javax.swing.JButton btnContinuar_Trns;
    private javax.swing.JButton btnDoRegistro;
    private javax.swing.JButton btnLimpiarResultados;
    private javax.swing.JButton btnListarCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea resultados_jTextArea;
    private javax.swing.JComboBox<String> tipoCuenta_jComboBox;
    private javax.swing.JComboBox<String> tipoRegistro_jComboBox;
    private javax.swing.JComboBox<String> tipoTransaccion_jComboBox;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtDocumento_Tran;
    private javax.swing.JTextField txtMonto_trns;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
